version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  mysql:
    build: ./db
    container_name: mysql
  flask-app:
    build: ./flask-app
    container_name: flask-app

  